// Datos Colombia: departamentos y ciudades (incluye cabeceras y ciudades principales).
// Nota: si quieres incluir MÁS municipios, este archivo es el único que se debe actualizar.

export const colombiaDepartamentos = [
  { code: 'AMA', name: 'Amazonas' },
  { code: 'ANT', name: 'Antioquia' },
  { code: 'ARA', name: 'Arauca' },
  { code: 'ATL', name: 'Atlántico' },
  { code: 'BOL', name: 'Bolívar' },
  { code: 'BOY', name: 'Boyacá' },
  { code: 'CAL', name: 'Caldas' },
  { code: 'CAQ', name: 'Caquetá' },
  { code: 'CAS', name: 'Casanare' },
  { code: 'CAU', name: 'Cauca' },
  { code: 'CES', name: 'Cesar' },
  { code: 'CHO', name: 'Chocó' },
  { code: 'COR', name: 'Córdoba' },
  { code: 'CUN', name: 'Cundinamarca' },
  { code: 'GUA', name: 'Guainía' },
  { code: 'GUV', name: 'Guaviare' },
  { code: 'HUI', name: 'Huila' },
  { code: 'MAG', name: 'Magdalena' },
  { code: 'MET', name: 'Meta' },
  { code: 'NAR', name: 'Nariño' },
  { code: 'NSA', name: 'Norte de Santander' },
  { code: 'PUT', name: 'Putumayo' },
  { code: 'QUI', name: 'Quindío' },
  { code: 'RIS', name: 'Risaralda' },
  { code: 'SAP', name: 'San Andrés y Providencia' },
  { code: 'SAN', name: 'Santander' },
  { code: 'SUC', name: 'Sucre' },
  { code: 'TOL', name: 'Tolima' },
  { code: 'VAC', name: 'Valle del Cauca' },
  { code: 'VAU', name: 'Vaupés' },
  { code: 'VID', name: 'Vichada' }
];

export const colombiaCiudadesPorDepartamento = {
  'AMA': ['Leticia'],
  'ANT': ['Medellín','Itagüí','Envigado','Bello','Apartadó','Carepa','Apartadó','Rionegro','Marinilla','Sabaneta','Turbo','Copacabana','Caldas','Medellín','Amagá'],
  'ARA': ['Arauca','Arauquita','Saravena'],
  'ATL': ['Barranquilla','Soledad','Malambo','Galapa','Puerto Colombia'],
  'BOL': ['Cartagena de Indias','Soledad','Arjona','Magangué','Turbaco','Turbana','Villanueva'],
  'BOY': ['Tunja','Sogamoso','Duitama','Chiquinquirá','Paipa','Moniquirá','Guateque'],
  'CAL': ['Manizales','Villamaría','La Dorada','Aguadas','Chinchiná'],
  'CAQ': ['Florencia','San Vicente del Caguán','El Doncello'],
  'CAS': ['Yopal','Aguazul','Tauramena','Villanueva','Monterrey'],
  'CAU': ['Popayán','Cajibío','Piendamó','Timbío','Patía (El Bordo)','Santander de Quilichao'],
  'CES': ['Valledupar','Aguachica','Codazzi','San Alberto','La Paz'],
  'CHO': ['Quibdó','Istmina','Bojayá','Belen de Bajirá','Condoto'],
  'COR': ['Montería','Cereté','Sahagún','Chimá','Lorica'],
  'CUN': ['Bogotá','Soacha','Chía','Cajicá','Zipaquirá','Facatativá','Madrid','Funza','Fusagasugá','Girardot'],
  'GUA': ['Inírida'],
  'GUV': ['San José del Guaviare','El Retorno','Calamar','Miraflores'],
  'HUI': ['Neiva','Garzón','Gigante','La Plata (Huila)','Pitalito'],
  'MAG': ['Santa Marta','Ciénaga','El Banco','Fundación','Aracataca'],
  'MET': ['Villavicencio','Acacías','Granada','Puerto López','San Martín'],
  'NAR': ['Pasto','Ipiales','Tumaco','Sandoná','Túquerres','La Cruz (Nariño)'],
  'NSA': ['Cúcuta','Villa del Rosario','Los Patios','El Zulia','Ocaña'],
  'PUT': ['Mocoa','Sibundoy','Puerto Asís','Villagarzón'],
  'QUI': ['Armenia','Calarcá','La Tebaida','Quimbaya'],
  'RIS': ['Pereira','Dosquebradas','Santa Rosa de Cabal','La Virginia'],
  'SAP': ['San Andrés','Providencia'],
  'SAN': ['Bucaramanga','Floridablanca','Girón','Piedecuesta','Barrancabermeja','San Gil'],
  'SUC': ['Sincelejo','San Marcos','Sampués','Morroa','Majagual'],
  'TOL': ['Ibagué','Espinal','Lérida','Melgar','Honda','Guamo'],
  'VAC': ['Cali','Palmira','Buenaventura','Jamundí','Cartago','Buga','Tuluá'],
  'VAU': ['Mitú'],
  'VID': ['Puerto Carreño']
};

